### ISSUE TITLE
Verify device login 

### ISSUE THREAD

**Issue by stevekenney318** [nayrk/Blink#11]
After running the script for the 1st time (which worked perfectly) .. I received an email from Blink to verify my device...  How would I go about doing this. It sounds like this will break this from working again.
--------

![20201026_123554_000077](https://user-images.githubusercontent.com/53465149/97200617-d49cc600-1787-11eb-9c4c-8f7159c37167.jpg)

**Comment by nayrk** [comment]
Fixed in latest code release from another user.

**Comment by stevekenney318** [comment]
> Fixed in latest code release from another user.
It actual ran fine before, even though I got that message. I prefer it not to cycle every 30 minutes.... I don't want to download every video... I usually go through and delete some before running it.  I have a bat file on my desktop that I just click on  - will the old script still work ?

**Comment by stevekenney318** [comment]
> Fixed in latest code release from another user.

oh crap, I just followed the link above by chrissv and learned the old script doesn't work anymore... that sucks. I guess now I'll have to input the PIN after I run it everytime.
