### ISSUE TITLE
Script stopped working

### ISSUE THREAD

**Issue by heIIo-world** [nayrk/Blink#13]
The script stopped working yesterday. Did something happen or am I doing something wrong?

Thank you!
JZ

**Comment by heIIo-world** [comment]
It seems to create the correct directories then download the thumbnails, but it won't download the videos. Could this be a problem with my individual account?

**Comment by chrissv** [comment]
Same for me. I get the "verify" email so this sounds the same as #11 and #7

**Comment by jeff-zacuto** [comment]
Interestingly, when I attempt to update my password in the app, it says "Password Update Failed." So I can't even change my password. Maybe something is up with Blink?

**Comment by heIIo-world** [comment]
So I have little to NO idea what I'm doing, but I'm going through the script line by line and removing all of the #'s so I can watch what happens for each command. It looks like authentication isn't the problem at all. It authenticates, returns the list of networks, downloads the thumbnails for each device, and then gets hung up on downloading the videos. It eventually just times out. 

I've tried changing the names of my networks to see if that makes any difference. The only difference it DOES make is that it will re-download the thumbnails, but then get hung up again on downloading the videos. 

So if nothing's changed in the script, maybe something changed on the server side?

**Comment by heIIo-world** [comment]
Also very strange is that I have NO videos prior to noon yesterday. They all start at 1201PM or later. As if everything before disappeared. Which is really weird. I think something's going on at Amazon now.

**Comment by petunia101** [comment]
Hi, my videos aren't downloading anymore either.  I will get the message saying "All new videos and thumbnails downloaded to C:\Users\xxxx\Desktop\Blink" but videos have NOT downloaded.  Also I am now getting the "verify" email with code from Blink which I had not been getting when the videos were downloading.  Blink must have changed something on their end (with the two factor authorization).

**Comment by heIIo-world** [comment]
I updated my thumbnails and it recognized that there were new ones and downloaded them, but when it got to the videos it just stops and eventually times out. So something changed with that part, I'm inclined to believe. But I ain't smart enough to figure out how to fix it. :)

**Comment by axid2006** [comment]
hello, 
same problem also with EU servers -> https://github.com/MattTW/BlinkMonitorProtocol/issues/49
Change in PIN Authentification protocol

**Comment by petunia101** [comment]
just FYI for anyone that needs to get their videos downloaded - there is another guy that created a whole Desktop Viewer that also downloads videos.  I am not a computer programming person at all so I can't tell you the differences between the "Nyark/Blink" script and the Desktop Viewer (other than I gather the script is transparent programming) but I can tell you that the Desktop Viewer program is working for me - there is actually a place where you can enter the 2FA code that Blink emails you when signing in....
 
Link to the other program info:  https://github.com/lurume84/bling-desktop

**Comment by heIIo-world** [comment]
Thanks! This is a great app all on its own, but what I really need is the ability to bulk download video clips from the cloud to a local computer. :( The script did that beautifully.

**Comment by petunia101** [comment]
Hi Jeff, 
just wanted to clarify, that the "Bling Desktop" program/app DOES bulk download the videos to my computer.  It doesn't do it anywhere near as quickly as the script did though.  The default parameters in the blink.ini file are set to download one video per minute I think, but you can change that.  I know the script was much less complicated to set up, but "Bling Desktop" is an option in the interim until the script gets working again.  (Blink Desktop also doesn't segregate downloaded videos by camera in case you have multiple cameras, but I am just happy to have something that automatically downloads videos)

**Comment by heIIo-world** [comment]
Oh! I didn't realize this, so that could be a great alternative for a bit! Yes, we have two Sync 2 modules with four cameras each, for a total of eight cameras. So we run out of cloud storage quickly, and can only store about 48-72 hours worth of footage.

**Comment by tyuhas** [comment]
I'm more of a hack than a dev but this chunk of code that I added after line #69 in the original script to prompt for the PIN and then send it to Blink seems to get the videos now.  I've run it a few times and it works for me at least

$clientID = $response.client.id

#echo $response
#echo $region
#echo $authToken
#echo $accountID

$pin = Read-Host -Prompt 'Input PIN'
$uri = 'https://rest-'+ $region +".immedia-semi.com/api/v4/account/"+ $accountID +'/client/'+ $clientID +"/pin/verify"
#Headers to send for PIN authentication
$pin_headers = @{
    "CONTENT_TYPE" = "application/json"
    "TOKEN_AUTH" = $authToken
}

#PIN goes in the body
$pin_body = @{
    "pin" = $pin
}

$response = Invoke-RestMethod -UseBasicParsing $uri -Method Post -Headers $pin_headers -Body $pin_body

**Comment by heIIo-world** [comment]
Thank you!!!

I get the prompt "Input PIN:" but I don't get emailed/texted a PIN. 

Did I do it wrong? :)

**Comment by tyuhas** [comment]
The PIN comes from the Blink system after a successful authentication.  It showed for me w/in a few minutes of running the script.  Maybe it's in your spam/junk folder?

**Comment by heIIo-world** [comment]
Got it working!!!! You, sir, are a genius!!! How can I/we repay you??

**Comment by heIIo-world** [comment]
Ah, but key question... Does it require the PIN every time the script is run? If so, it can't be autorun with Scheduler.

**Comment by tyuhas** [comment]
From what I understand, a PIN is only good for a 40-minute window where you can create a new connection (i.e. each fresh run of the script).  Existing connections will stay live beyond that which is how I think Bling-desktop works (it stays connected to the servers as long as you have the app running).  I'm not sure how this particular script could be modified to do that since it's pretty much designed to run, grab videos, and exit.

**Comment by heIIo-world** [comment]
But we're a step closer!!! :) Thank you for your help!

**Comment by heIIo-world** [comment]
What would also be cool is a trigger system where when motion is detected a script waits for the video to finish recording, then downloads it automatically.

**Comment by nayrk** [comment]
@tyuhas Thanks for the fix. I haven't been keeping this script up to date as I am no longer using Blink extensively myself anymore. I will merge in your fix.

@jeff-zacuto I have updated the script to re-run every 30 minutes infinitely so that it will only prompt you the first time you run it manually. You won't be able to run this on Windows scheduler anymore.

**Comment by heIIo-world** [comment]
You guys are fantastic!!!! Thank you so, so much!
