### ISSUE TITLE
"message":"An app update is required"

### ISSUE THREAD

**Issue by Breckmorrison** [nayrk/Blink#15]
Started receiving error today after using it without any issue for over a month.  I checked password by login out/in on my blink app and it works fine. 

Invoke-RestMethod : {"message":"An app update is required"}
At E:\BlinkDownload.ps1:61 char:13
+ $response = Invoke-RestMethod -UseBasicParsing $uri -Method Post -Hea ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invalid credentials provided. Please verify email and password.
Press Enter to continue...:

**Comment by petunia101** [comment]
For what it's worth, I am getting the same error message now (and was also working fine lately).
I'm not a programmer so no clue on how to fix....

**Comment by stevekenney318** [comment]
Yep, looks like Amazon broke it, I'm getting the same message

**Comment by heIIo-world** [comment]
Long story short, I don't think they broke it at all. Yesterday Amazon launched its Blink storage subscription options. So my guess is that they've shut down the APIs altogether. 

https://www.amazon.com/b?node=21154643011

**Comment by stevekenney318** [comment]
> Long story short, I don't think they broke it at all. Yesterday Amazon launched its Blink storage subscription options. So my guess is that they've shut down the APIs altogether.


Well, I plan to differ ... the script worked, they changed something, therefore they broke it.

**Comment by stevekenney318** [comment]
> https://www.amazon.com/b?node=21154643011

Those greedy mofo's ... so what does this mean for us now ? Do we have to subscribe and pay money to store videos ?

**Comment by ttteee90** [comment]
Just found this project yesterday,  Bad timing on my part.
Had some difficulty locating the current working source (with Pin) but looks like the current is also broken.

With what I have, I was able to get passed "An app update is required" by changing the URI from "v4" to "v5" on (my) line # 59 
but other unauth errors.

Code around it looks like ,,,,

> # Login URL of Blink API
> #$uri = "https://$blinkAPIServer/api"
> $uri = "https://rest-prod.immedia-semi.com/api/v5/account/login"

**Comment by ttteee90** [comment]
I'm having some success ...  this last execution is downloading my videos.

Tried a bunch of stuff. Will share after a bit more testing.

**Comment by stevekenney318** [comment]
> I'm having some success ... this last execution is downloading my videos.
> 
> Tried a bunch of stuff. Will share after a bit more testing.

That's great to hear. Good luck getting the rest of the way !

**Comment by ttteee90** [comment]
Cleaned it up a bit but still a mess with my trial and errors.  Some cleanup will be needed.

But It's working for me.  


[Updated031921-BlinkVideoDownloader_.zip](https://github.com/nayrk/Blink/files/6174429/Updated031921-BlinkVideoDownloader_.zip)

Worked out the login URI needs to be V5...
The PIN URI needed to be the region/tier
Attempted to specify a login unique_id, Doc said it was optional. Wondered if it is now required. I left it in because it's working.
Finally, the get list of networks/cameras needed to be region/tier.

**Comment by stevekenney318** [comment]
> Cleaned it up a bit but still a mess with my trial and errors. Some cleanup will be needed.
> 
> But It's working for me.
> 
> [Updated031921-BlinkVideoDownloader_.zip](https://github.com/nayrk/Blink/files/6174429/Updated031921-BlinkVideoDownloader_.zip)
> 
> Worked out the login URI needs to be V5...
> The PIN URI needed to be the region/tier
> Attempted to specify a login unique_id, Doc said it was optional. Wondered if it is now required. I left it in because it's working.
> Finally, the get list of networks/cameras needed to be region/tier.

Thanks @ttteee90 !!   I put my info in the script, and then my PIN when requested and it worked great !

![20210319_201125_000423](https://user-images.githubusercontent.com/53465149/111853005-867f8f00-88ef-11eb-882d-145feccc6236.jpg)

**Comment by stevekenney318** [comment]
and still working ... 
![image](https://user-images.githubusercontent.com/53465149/111856720-14b14080-8903-11eb-8514-ad94ecf401d6.png)

**Comment by Breckmorrison** [comment]
Working for me as well.  Thanks everyone.  I made some additional local changes to add the camera name to the filename instead of a directory.

**Comment by ttteee90** [comment]
Great news guys.  Any maintainer of this repository can take those changes (clean up my mess) and merge with master.

**Comment by stevekenney318** [comment]
> Working for me as well. Thanks everyone. I made some additional local changes to add the camera name to the filename instead of a directory.

So, all your pictures go into one folder and the camera name is in the file name ? I think I might like that option !

**Comment by Breckmorrison** [comment]
Yes.... The new names are "2021-03-19_10-58-59_Home Camera.mp4"  at the root of your

my changes.....  gave 2 options for camera name first, then timestamp, or visa versa.  I like timestamp first, then camera, but the other is there commented out.

```
			# Download video if it is new
#			$path = "$saveDirectory\Blink\$network\$camera"
			$path = "$saveDirectory\Blink"
#			$videoPath = "$path\$camera_id-$videoTime.mp4"
#			$videoPath = $path +'\'+ $camera +'_'+ $videoTime +'.mp4'
			$videoPath = $path +'\'+ $videoTime +'_'+ $camera +'.mp4'
```

**Comment by stevekenney318** [comment]
> Yes.... The new names are "2021-03-19_10-58-59_Home Camera.mp4" at the root of your
> 
> my changes..... gave 2 options for camera name first, then timestamp, or visa versa. I like timestamp first, then camera, but the other is there commented out.
> 
> ```
> 			# Download video if it is new
> #			$path = "$saveDirectory\Blink\$network\$camera"
> 			$path = "$saveDirectory\Blink"
> #			$videoPath = "$path\$camera_id-$videoTime.mp4"
> #			$videoPath = $path +'\'+ $camera +'_'+ $videoTime +'.mp4'
> 			$videoPath = $path +'\'+ $videoTime +'_'+ $camera +'.mp4'
> ```

I like date time first, as that's how I usually name all of my files like screen captures etc 

Thanks so much

**Comment by nayrk** [comment]
Thanks for the fix @ttteee90
I cleaned up the code a bit and merged it into the master.
