### ISSUE TITLE
Script stopped downloading videos

### ISSUE THREAD

**Issue by Breckmorrison** [nayrk/Blink#18]
The script stopped downloading videos.  I put in some comments to try and see where it is failing.  It is getting the network name and all of the cameras, but when trying to loop over the videos, nothing downloads.  It also is not throwing any errors.  Just acting like is downloaded them and then goes into the 30 min wait state.  

Anyone else seeing this issue?

**Comment by stevekenney318** [comment]
mine is working fine.  A while ago I changed it to only checking every 3
hours... Gives me some time to delete ones I don't need (from the app).
[image: 20210822_213207_000945.jpg]

**Comment by Breckmorrison** [comment]
I found the issue... It was a VM mapping issue..  thanks for response.  Closing

**Comment by stevekenney318** [comment]
Glad to hear it!

**Comment by stevekenney318** [comment]
@Breckmorrison @nayrk ,

Hi, can you help with this ... https://github.com/nayrk/Blink/issues/19

the program is not downloading thumbnail images anymore....

Thanks, Steve

![20220323_081422_001840](https://user-images.githubusercontent.com/53465149/159697052-aad561be-9bc1-495f-af62-da953a97293f.jpg)
