### ISSUE TITLE
Excellent! [[NOT AN ISSUE]]

### ISSUE THREAD

**Issue by rekcah216** [nayrk/Blink#4]
This is awesome, saved me quite a bit of time. Thanks much!

**Comment by nayrk** [comment]
> This is awesome, saved me quite a bit of time. Thanks much!

No problem. Pull the new code to handle the change with Blink's authentication.

**Comment by MauiYow** [comment]
EXCELLENT!! I've spent a lot of time looking for this solution. Much appreciated! I'm glad you didn't let this script die.

**Comment by axid2006** [comment]
thx - works perfect!!!!
