### ISSUE TITLE
Does this work now the new API is in force at Blink?

### ISSUE THREAD

**Issue by fergusrobertson** [nayrk/Blink#6]

**Comment by fergusrobertson** [comment]
Notice: Disabling Unauthorized 3rd Party Automation Scripts | Notice: Disabling Unauthorized 3rd Party Automation Scripts | Notice: Disabling Unauthorized 3rd Party Automation Scripts |   |   |  
-- | -- | -- | -- | -- | --
Notice: Disabling Unauthorized 3rd Party Automation Scripts | Notice: Disabling Unauthorized 3rd Party Automation Scripts |  
Notice: Disabling Unauthorized 3rd Party Automation Scripts
 
  |  
 
 
Dear Blink Customer, You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | Dear Blink Customer, You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | Dear Blink Customer, You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | Dear Blink Customer, | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | Thank you, Team Blink
Dear Blink Customer, You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | Dear Blink Customer, You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | Dear Blink Customer, | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | Thank you, Team Blink
Dear Blink Customer, You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | Dear Blink Customer, | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | Thank you, Team Blink
Dear Blink Customer,
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, Team Blink | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | Thank you, Team Blink
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration.
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration.
Thank you, Team Blink
  |   |  
 
 
 
2020  Amazon.com, inc. or its affiliates. All rights reserved. Amazon, Blink, and all related logos are trademarks of Amazon.com, Inc. or its affiliates.Our mailing address is:Blink for Home by Amazon100 Riverpark Dr,North Reading, MA 01864 | 2020  Amazon.com, inc. or its affiliates. All rights reserved. Amazon, Blink, and all related logos are trademarks of Amazon.com, Inc. or its affiliates.Our mailing address is:Blink for Home by Amazon100 Riverpark Dr,North Reading, MA 01864 | 2020  Amazon.com, inc. or its affiliates. All rights reserved. Amazon, Blink, and all related logos are trademarks of Amazon.com, Inc. or its affiliates.Our mailing address is:Blink for Home by Amazon100 Riverpark Dr,North Reading, MA 01864
2020  Amazon.com, inc. or its affiliates. All rights reserved. Amazon, Blink, and all related logos are trademarks of Amazon.com, Inc. or its affiliates.Our mailing address is:Blink for Home by Amazon100 Riverpark Dr,North Reading, MA 01864 | 2020  Amazon.com, inc. or its affiliates. All rights reserved. Amazon, Blink, and all related logos are trademarks of Amazon.com, Inc. or its affiliates.Our mailing address is:Blink for Home by Amazon100 Riverpark Dr,North Reading, MA 01864
2020  Amazon.com, inc. or its affiliates. All rights reserved. Amazon, Blink, and all related logos are trademarks of Amazon.com, Inc. or its affiliates.Our mailing address is:Blink for Home by Amazon100 Riverpark Dr,North Reading, MA 01864

**Comment by nayrk** [comment]
Yes, please use the new code.

**Comment by fergusrobertson** [comment]
Thanks for responding.  I edited the new code changing my download directory and adding my email and password only and I got. 

Invoke-RestMethod : {"code":200,"message":"Invalid credentials"}
At D:\Blink\newblink.ps1:59 char:13
+ $response = Invoke-RestMethod -UseBasicParsing $uri -Method Post -Hea ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invalid credentials provided. Please verify email and password.
Press Enter to continue...:

**Comment by fergusrobertson** [comment]
My IFTTT account is linked to my google account if that makes a difference.

**Comment by nayrk** [comment]
Did you activate the two factor authentication for your account with Blink yet? If you haven't, you will need to. Blink will send an email with some code to enter when it is activated. There are steps on how activate it on Blink's support forum. 

Please also double check your email and password are correct.
