### ISSUE TITLE
sync_unit/network_name for loop

### ISSUE THREAD

**Issue by adrpibgal** [nayrk/Blink#8]
In this section it looks like the sync_unit name is set to the default network name or assumes one network/system for each sync module/unit:

foreach($sync_unit in $sync_units.networks)
{
    $network_id = $sync_unit.network_id
    $networkName = $sync_unit.name

I have some Blink Minis set up on the same sync module but different networks/systems so can the network for loop be updated to also go through and download the other networks/systems on the same sync module? I have grouped cameras into different networks/systems to have more flexible control over which specific areas are armed/disarmed instead of just all cameras at the same time.

![BlinkSystems](https://user-images.githubusercontent.com/66967704/86207440-2d3eb800-bb34-11ea-8f24-527b5d0ccf5c.png)

I have also tested adding a Blink Mini to the same network/system with just XT2 cameras but I'm not seeing the Blink Mini videos being downloaded this way either, it seems like this may be related to the endpoint used? The new video flag on the saved Blink Mini videos however goes away on my phone after running the code so maybe something else?

"# Get list of networks
#$uri = "https://rest-u017.immedia-semi.com/api/v1/camera/usage"
$uri = 'https://rest-'+ $region +".immedia-semi.com/api/v1/camera/usage"
#echo $uri"

Otherwise works very well, I'm bouncing between this code and BlinkPy. I prefer the folder organization and updating the timestamps to local time done with this code.

**Comment by nayrk** [comment]
Sorry, I don't have a Blink mini to test myself so I am unable to identify the structure to debug for you.
