### ISSUE TITLE
Invoke-RestMethod : {"message":"Unauthorized Access","code":101}

### ISSUE THREAD

**Issue by locvez** [nayrk/Blink#9]
This has been working okay for me over the last week or two but I now get the following error: - I have made no changes to the script.

> Invoke-RestMethod : {"message":"Unauthorized Access","code":101}
> At N:\media\camera\BlinkVideoDownloader.ps1:89 char:15
> + ... ync_units = Invoke-RestMethod -UseBasicParsing $uri -Method Get -Head ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> Invoke-RestMethod : {"message":"Unauthorized Access","code":101}
> At N:\media\camera\BlinkVideoDownloader.ps1:139 char:17
> + ... $response = Invoke-RestMethod -UseBasicParsing $uri -Method Get -Head ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by TeagenSirrus** [comment]
I am getting the same error.
Why won't the let us just mass download with ease?!

**Comment by locvez** [comment]
To resolve the issue, comment out line 78 shown below. I have forked and submitted a pull request to fix this issue.

```
# Headers to send to Blink's server after authentication with our token
$headers = @{
   # "Host" = "$blinkAPIServer" <- THIS is line 78, comment this out. Now it works
    "TOKEN_AUTH" = "$authToken"
}
```

**Comment by locvez** [comment]
clicked close in error.

**Comment by nayrk** [comment]
Thanks.
